@url=http://localhost:3000

### Listado de tareas
GET {{url}}/tareas

### Buscar tarea por ID
GET {{url}}/tareas/

### Crear tarea
POST {{url}}/tareas
Content-Type: application/json

{
  "nombre" : "leer",
  "completada" : false
}

### Obtener las tareas completadas o pendientes
GET {{url}}/tareas?completada=true

### Actualizar tarea por ID
PUT {{url}}/tareas/1
Content-Type: application/json

{
  "nombre": "cocinar",
  "completada": false
}

### Eliminar tarea por ID
DELETE {{url}}/tareas/6
