@url = http://localhost:3000

### Listado de alumnos
GET {{url}}/alumnos

### Buscar alumno por ID
GET {{url}}/alumnos/2

### Crear alumno
POST {{url}}/alumnos
Content-Type: application/json

{
  "nombre": "jose",
  "materia_id": 3,
  "nota1": 4,
  "nota2": 5,
  "nota3": 9
}

### Editar alumno
PUT {{url}}/alumnos/4
Content-Type: application/json

{
  "nombre": "mono",
  "materia_id": 4,
  "nota1": 9,
  "nota2": 7,
  "nota3": 10
}

### Borrar alumno
DELETE {{url}}/alumnos/1
